configurations:

    # SwiftRoonAPI
    - sources:
        - ./SwiftRoonAPI/SwiftRoonAPI
      templates:
        - ./Sourcery/Templates/AutoMockable.stencil
      output:
        ./SwiftRoonAPI/Tests/Mocks/Generated

    # TransportAPI
    - sources:
        - ./TransportAPI/TransportAPI
      templates:
        - ./Sourcery/Templates/AutoMockable.stencil
      output:
        ./TransportAPI/Tests/Mocks/Generated