name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
    
  test: 
    runs-on: macos-13
    permissions: read-all
    steps:
    - name: Swift version
      run: |
        swift --version
    - uses: actions/checkout@v3
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository. 
      with:
        ssh-private-key: |
          ${{ secrets.LOGGER }}
        repo-mappings: |
          github.com/Slorq/SwiftLogger
    - name: Build package
      run: |
        swift build 
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          core:
            - 'SwiftRoonAPICore/**'
          swift-roon-api:
            - 'SwiftRoonAPI/**'
          transport-api:
            - 'TransportAPI/**'
    - name: Run Core tests
      run: |
        swift test --enable-code-coverage --filter SwiftRoonAPICoreTests
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftRoonAPIPackageTests.xctest/Contents/MacOS/SwiftRoonAPIPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" SwiftRoonAPICore > core.lcov
    - name: Run SwiftRoonAPI tests
      if: steps.changes.outputs.swift-roon-api == 'true'
      run: |
        swift test --enable-code-coverage --filter "SwiftRoonAPITests|SwiftRoonAPICoreTests"
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftRoonAPIPackageTests.xctest/Contents/MacOS/SwiftRoonAPIPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" SwiftRoonAPI > swift-roon-api.lcov
    - name: Run TransportAPI tests
      if: steps.changes.outputs.transport-api == 'true'
      run: |
        swift test --enable-code-coverage --filter "RoonTransportAPITests|SwiftRoonAPICoreTests"
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftRoonAPIPackageTests.xctest/Contents/MacOS/SwiftRoonAPIPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" TransportAPI > transport.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./core.lcov, ./swift-roon-api.lcov, transport.lcov
        fail_ci_if_error: true
        verbose: true
