# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout: 
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

  build:
    runs-on: macos-latest
    needs: checkout
    steps:
    - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository. 
      with:
        ssh-private-key: |
          ${{ secrets.LOGGER }}
        repo-mappings: |
          github.com/Slorq/SwiftLogger
      
    - name: Build
      run: swift build

  test:
    runs-on: macos-latest
    needs: [checkout, build]
    steps:    
    - name: Run tests
      run: swift test
