# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.changes.outputs.core }}
      swift-roon-api: ${{ steps.changes.outputs.swift-roon-api }}
      transport-api: ${{ steps.changes.outputs.transport-api }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          core:
            - 'SwiftRoonAPICore/**'
          swift-roon-api:
            - 'SwiftRoonAPI/**'
          transport-api:
            - 'TransportAPI/**'  

  test-core: 
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Run Core tests
      run: |
        swift test --enable-code-coverage --filter SwiftRoonAPICoreTests
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftRoonAPIPackageTests.xctest/Contents/MacOS/SwiftRoonAPIPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" SwiftRoonAPICore > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: info.lcov
        fail_ci_if_error: true
        verbose: true

  test-swift-roon-api: 
    needs: changes
    if: ${{ needs.changes.outputs.swift-roon-api == 'true' }}
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository. 
      with:
        ssh-private-key: |
          ${{ secrets.LOGGER }}
        repo-mappings: |
          github.com/Slorq/SwiftLogger
    - name: Run SwiftRoonAPI tests
      run: |
        swift test --enable-code-coverage --filter SwiftRoonAPITests
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftRoonAPIPackageTests.xctest/Contents/MacOS/SwiftRoonAPIPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" SwiftRoonAPI > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: info.lcov
        fail_ci_if_error: true
        verbose: true

  test-transport-api: 
    needs: changes
    if: ${{ needs.changes.outputs.transport-api == 'true' }}
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository. 
      with:
        ssh-private-key: |
          ${{ secrets.LOGGER }}
        repo-mappings: |
          github.com/Slorq/SwiftLogger
    - name: Run TransportAPI tests
      run: |
        swift test --enable-code-coverage --filter RoonTransportAPITests
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftRoonAPIPackageTests.xctest/Contents/MacOS/SwiftRoonAPIPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" TransportAPI > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: info.lcov
        fail_ci_if_error: true
        verbose: true
